[options]
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons
data_dir = /var/lib/odoo
admin_passwd = $pbkdf2-sha512$600000$oNT6P.ccw3gvBeB8D2FM6Q$g/LLQixFWbZVJIEgNuiEdDpePMtUp42RqBPo9r2lUkO1qV0mR71SQavyYMeu1AUDpf1Qpx88GwUf3QTzXU00GQ
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo_secret
db_name = False
list_db = True
proxy_mode = True
without_demo = all
limit_memory_hard = 2684354560
limit_memory_soft = 2147483648
limit_time_cpu = 600
limit_time_real = 1200
max_cron_threads = 1
workers = 2

